### ISSUE TITLE
Crashes if the prompt is too long.

### ISSUE THREAD

**Issue by PeterCamilleri** [PeterCamilleri/mysh#70]
Ooops. I tried:

    set $prompt = $w $d $t $r

A reduced stack trace follows.

    from /lib/mysh/sources/console.rb:34:in `get'
    from /lib/mysh/sources/console.rb:17:in `get_command'
    from /lib/mysh/user_input.rb:16:in `get_command'
    from /lib/mysh/process.rb:24:in `process_source'
    from /lib/mysh/process.rb:8:in `process_console'

**Comment by PeterCamilleri** [comment]
Pending.
