### ISSUE TITLE
Crashes if a variable is used twice.

### ISSUE THREAD

**Issue by PeterCamilleri** [PeterCamilleri/mysh#71]
The entry:

    set $prompt = $r $r

Causes:

/lib/mysh/shell_variables/shell_variable_keeper.rb:17:in `get_value': 
Mysh variable looping error. (RuntimeError)

        from /lib/mysh/shell_variables/shell_variable_store.rb:21:in `[]'
        from /lib/mysh/shell_variables/evaluate.rb:19:in `block in eval_variables'
        from /lib/mysh/shell_variables/evaluate.rb:17:in `gsub'
        from /lib/mysh/shell_variables/evaluate.rb:17:in `eval_variables'
        from /lib/mysh/pre_processor.rb:8:in `preprocess'
        from /lib/mysh/shell_variables/shell_variable_keeper.rb:20:in `get_value'
        from /lib/mysh/shell_variables/shell_variable_store.rb:24:in `[]'

**Comment by PeterCamilleri** [comment]
Pending.
